binding/webgl_extensions.cc, binding/webgl_extensions.h, binding/webgl_rendering_context.cc, src/tests/half_float_texture_upload_test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/5)
=> Fix half-float demo

binding/webgl_extensions.cc, binding/webgl_extensions.h, binding/webgl_rendering_context.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/7)
=> Cleanup more extension subclasses.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/8)
=> Cleanup the README for test/examples

binding/binding.cc, binding/webgl_extensions.cc, binding/webgl_extensions.h, binding/webgl_rendering_context.cc, scripts/install.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/10)
=> Add EXT_color_buffer_*float and cleanup WebGL extensions

binding/egl_context_wrapper.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/11)
=> WIP - Mac OS eglPlatform loading

binding/egl_context_wrapper.cc, binding/egl_context_wrapper.h, binding/webgl_rendering_context.cc, binding/webgl_rendering_context.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/15)
=> glBindAttribLocation

binding/egl_context_wrapper.cc, binding/webgl_rendering_context.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/20)
=> Init with EGL_PLATFORM_ANGLE_TYPE_OPENGLES_ANGLE on ARM devices.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/22)
=> Show how to create WebGL context

binding/binding.cc, binding/webgl_extensions.cc, binding/webgl_extensions.h, binding/webgl_rendering_context.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/29)
=> Wire in more WebGL extensions

.vscode/c_cpp_properties.json, binding/binding.cc, binding/webgl_extensions.cc, binding/webgl_extensions.h, binding/webgl_rendering_context.cc, src/tests/test_utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/30)
=> Extension name cleanup.

binding/binding.cc, binding/webgl_extensions.cc, binding/webgl_extensions.h, binding/webgl_rendering_context.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/31)
=> Add more trivial WebGL extensions

binding/egl_context_wrapper.cc, binding/egl_context_wrapper.h, binding/webgl_extensions.cc, binding/webgl_rendering_context.cc, scripts/install.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/32)
=> Upgrade Linux to ANGLE/Chromium-3683 & use local headers

scripts/install.js
Built with the following settings:
```
is_debug = false
is_component_build = true
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/36)
=> Update ANGLE builds

scripts/install.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/42)
=> Turn off caching when downloading ANGLE.

binding/webgl_rendering_context.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/48)
=> Prevision->Precision

binding/webgl_rendering_context.cc
Just added the ones needed for three.js unsure if there are more that should be added here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/47)
=> Add more parameters to getParameters

binding/binding.cc, binding/webgl_extensions.cc, binding/webgl_extensions.h, binding/webgl_rendering_context.cc
Adds support for the instanced arrays extension
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/49)
=> Add ANGLE_instanced_arrays support

binding/webgl_rendering_context.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/52)
=> Fix glUniform3f

binding/webgl_extensions.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/54)
=> Swap min/max

package.json, yarn.lock
https://github.com/google/node-gles/network/alert/yarn.lock/minimist/open
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/node-gles/69)
=> Update tar to fix this minimist security warning.
